export type AutomationKind = 'playwright' | 'api' | 'manual';

export interface RegistryEntry {
  caseId: number;
  tcId: string; // e.g. "TC-06"
  module: string; // e.g. "Tasks & Automations"
  kind: AutomationKind;
  /** Playwright test tag that maps back to this case, e.g. '@case-62163' (kind === 'playwright' only). */
  tag?: string;
  /** Relative path to the spec file that covers this case (kind === 'playwright' only). */
  specFile?: string;
  /** Relative path to the API test module that covers this case (kind === 'api' only). */
  apiScript?: string;
}

// Populated incrementally as /qa-scripter (or the API-test builder) covers each case.
// One entry per automated TestRail case. Manual cases are never added here.
export const REGISTRY: RegistryEntry[] = [
  {
    caseId: 61988,
    tcId: 'TC-06',
    module: 'Tasks & Automations',
    kind: 'playwright',
    tag: '@case-61988',
    specFile: 'tests/tasks.spec.ts',
  },
  {
    caseId: 61989,
    tcId: 'TC-07',
    module: 'Tasks & Automations',
    kind: 'playwright',
    tag: '@case-61989',
    specFile: 'tests/tasks.spec.ts',
  },
  {
    caseId: 61996,
    tcId: 'TC-14',
    module: 'Tasks & Automations',
    kind: 'playwright',
    tag: '@case-61996',
    specFile: 'tests/tasks.spec.ts',
  },
  {
    caseId: 61967,
    tcId: 'TC-12',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61967',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61969,
    tcId: 'TC-13',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61969',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61973,
    tcId: 'TC-14',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61973',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61977,
    tcId: 'TC-15',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61977',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61978,
    tcId: 'TC-16',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61978',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61979,
    tcId: 'TC-17',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61979',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61980,
    tcId: 'TC-18',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61980',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61981,
    tcId: 'TC-19',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61981',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 61982,
    tcId: 'TC-20',
    module: 'Projects',
    kind: 'playwright',
    tag: '@case-61982',
    specFile: 'tests/projects.spec.ts',
  },
  {
    caseId: 62167,
    tcId: 'TC-01',
    module: 'Tools',
    kind: 'playwright',
    tag: '@case-62167',
    specFile: 'tests/tools.spec.ts',
  },
  {
    caseId: 61934,
    tcId: 'TC-16',
    module: 'Chat',
    kind: 'playwright',
    tag: '@case-61934',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61935,
    tcId: 'TC-17',
    module: 'Chat',
    kind: 'playwright',
    tag: '@case-61935',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61943,
    tcId: 'TC-18',
    module: 'Chat',
    kind: 'playwright',
    tag: '@case-61943',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61944,
    tcId: 'TC-07',
    module: 'Chat',
    kind: 'playwright',
    tag: '@case-61944',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61945,
    tcId: 'TC-19',
    module: 'Chat',
    kind: 'playwright',
    tag: '@case-61945',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61908,
    tcId: 'TC-20',
    module: 'Agent Management',
    kind: 'playwright',
    tag: '@case-61908',
    specFile: 'tests/chat.spec.ts',
  },
  {
    caseId: 61954,
    tcId: 'TC-01',
    module: 'Workspace',
    kind: 'playwright',
    tag: '@case-61954',
    specFile: 'tests/workspace.spec.ts',
  },
  {
    caseId: 61955,
    tcId: 'TC-02',
    module: 'Workspace',
    kind: 'playwright',
    tag: '@case-61955',
    specFile: 'tests/workspace.spec.ts',
  },
  {
    caseId: 61961,
    tcId: 'TC-03',
    module: 'Workspace',
    kind: 'playwright',
    tag: '@case-61961',
    specFile: 'tests/workspace.spec.ts',
  },
  {
    caseId: 61964,
    tcId: 'TC-04',
    module: 'Workspace',
    kind: 'playwright',
    tag: '@case-61964',
    specFile: 'tests/workspace.spec.ts',
  },
  {
    caseId: 61966,
    tcId: 'TC-05',
    module: 'Workspace',
    kind: 'playwright',
    tag: '@case-61966',
    specFile: 'tests/workspace.spec.ts',
  },
  {
    caseId: 62031,
    tcId: 'TC-11',
    module: 'Skills',
    kind: 'playwright',
    tag: '@case-62031',
    specFile: 'tests/skills.spec.ts',
  },
  {
    caseId: 62040,
    tcId: 'TC-12',
    module: 'Skills',
    kind: 'playwright',
    tag: '@case-62040',
    specFile: 'tests/skills.spec.ts',
  },
  {
    caseId: 62038,
    tcId: 'TC-13',
    module: 'Skills',
    kind: 'playwright',
    tag: '@case-62038',
    specFile: 'tests/skills.spec.ts',
  },
  {
    caseId: 62037,
    tcId: 'TC-14',
    module: 'Skills',
    kind: 'playwright',
    tag: '@case-62037',
    specFile: 'tests/skills.spec.ts',
  },
  {
    caseId: 62053,
    tcId: 'TC-12',
    module: 'Sub-agents',
    kind: 'playwright',
    tag: '@case-62053',
    specFile: 'tests/subagents.spec.ts',
  },
  {
    caseId: 62055,
    tcId: 'TC-13',
    module: 'Sub-agents',
    kind: 'playwright',
    tag: '@case-62055',
    specFile: 'tests/subagents.spec.ts',
  },
  {
    caseId: 62050,
    tcId: 'TC-14',
    module: 'Sub-agents',
    kind: 'playwright',
    tag: '@case-62050',
    specFile: 'tests/subagents.spec.ts',
  },
  {
    caseId: 62074,
    tcId: 'TC-09',
    module: 'Messaging',
    kind: 'playwright',
    tag: '@case-62074',
    specFile: 'tests/messaging.spec.ts',
  },
  {
    caseId: 62072,
    tcId: 'TC-10',
    module: 'Messaging',
    kind: 'playwright',
    tag: '@case-62072',
    specFile: 'tests/messaging.spec.ts',
  },
  {
    caseId: 62090,
    tcId: 'TC-02',
    module: 'Agent Configuration',
    kind: 'playwright',
    tag: '@case-62090',
    specFile: 'tests/agentConfig.spec.ts',
  },
  {
    caseId: 62091,
    tcId: 'TC-03',
    module: 'Agent Configuration',
    kind: 'playwright',
    tag: '@case-62091',
    specFile: 'tests/agentConfig.spec.ts',
  },
  {
    caseId: 62098,
    tcId: 'TC-04',
    module: 'Agent Configuration',
    kind: 'playwright',
    tag: '@case-62098',
    specFile: 'tests/agentConfig.spec.ts',
  },
  {
    caseId: 62099,
    tcId: 'TC-05',
    module: 'Agent Configuration',
    kind: 'playwright',
    tag: '@case-62099',
    specFile: 'tests/agentConfig.spec.ts',
  },
  {
    caseId: 62095,
    tcId: 'TC-06',
    module: 'Agent Configuration',
    kind: 'playwright',
    tag: '@case-62095',
    specFile: 'tests/agentConfig.spec.ts',
  },
  {
    caseId: 62122,
    tcId: 'TC-01',
    module: 'Security',
    kind: 'playwright',
    tag: '@case-62122',
    specFile: 'tests/security.spec.ts',
  },
  {
    caseId: 62121,
    tcId: 'TC-02',
    module: 'Security',
    kind: 'playwright',
    tag: '@case-62121',
    specFile: 'tests/security.spec.ts',
  },
  {
    caseId: 62134,
    tcId: 'TC-03',
    module: 'Security',
    kind: 'playwright',
    tag: '@case-62134',
    specFile: 'tests/security.spec.ts',
  },
  {
    caseId: 62127,
    tcId: 'TC-04',
    module: 'Security',
    kind: 'playwright',
    tag: '@case-62127',
    specFile: 'tests/security.spec.ts',
  },
  {
    caseId: 62203,
    tcId: 'TC-01',
    module: 'Concurrency & Chaos',
    kind: 'playwright',
    tag: '@case-62203',
    specFile: 'tests/concurrency.spec.ts',
  },
  {
    caseId: 62212,
    tcId: 'TC-02',
    module: 'Concurrency & Chaos',
    kind: 'playwright',
    tag: '@case-62212',
    specFile: 'tests/concurrency.spec.ts',
  },
  {
    caseId: 62150,
    tcId: 'TC-01',
    module: 'Profile & Settings',
    kind: 'playwright',
    tag: '@case-62150',
    specFile: 'tests/profile.spec.ts',
  },
  {
    caseId: 62152,
    tcId: 'TC-02',
    module: 'Profile & Settings',
    kind: 'playwright',
    tag: '@case-62152',
    specFile: 'tests/profile.spec.ts',
  },
  {
    caseId: 62154,
    tcId: 'TC-03',
    module: 'Profile & Settings',
    kind: 'playwright',
    tag: '@case-62154',
    specFile: 'tests/profile.spec.ts',
  },
  {
    caseId: 62161,
    tcId: 'TC-04',
    module: 'Profile & Settings',
    kind: 'playwright',
    tag: '@case-62161',
    specFile: 'tests/profile.spec.ts',
  },
  {
    caseId: 61920,
    tcId: 'TC-01',
    module: 'Dashboard',
    kind: 'playwright',
    tag: '@case-61920',
    specFile: 'tests/dashboard.spec.ts',
  },
  {
    caseId: 61924,
    tcId: 'TC-02',
    module: 'Dashboard',
    kind: 'playwright',
    tag: '@case-61924',
    specFile: 'tests/dashboard.spec.ts',
  },
  {
    caseId: 61931,
    tcId: 'TC-03',
    module: 'Dashboard',
    kind: 'playwright',
    tag: '@case-61931',
    specFile: 'tests/dashboard.spec.ts',
  },
  {
    caseId: 61932,
    tcId: 'TC-04',
    module: 'Dashboard',
    kind: 'playwright',
    tag: '@case-61932',
    specFile: 'tests/dashboard.spec.ts',
  },
];

export function getEntry(caseId: number): RegistryEntry | undefined {
  return REGISTRY.find((e) => e.caseId === caseId);
}

export function isScripted(caseId: number): boolean {
  return getEntry(caseId) !== undefined;
}

/** Given today's in-scope case IDs, returns the ones with no registry entry yet. */
export function unscriptedOf(caseIds: number[]): number[] {
  return caseIds.filter((id) => !isScripted(id));
}

export function scriptedOf(caseIds: number[]): RegistryEntry[] {
  return caseIds.map((id) => getEntry(id)).filter((e): e is RegistryEntry => e !== undefined);
}
